name: Gradle Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gradle-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Run Gradle Check
        run: |
          ./gradlew check --no-daemon --stacktrace
